version: "2"

services:
  wordpress:
    image: wordpress:5.9-php7.3-apache
    volumes:
      - .:/var/www/html/wp-content/themes/wordpress-test
      - ./docker/plugins:/var/www/html/wp-content/plugins
      - ./docker/uploads:/var/www/html/wp-content/uploads
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true );
        define('WP_DEBUG_LOG', true );
        define('WP_DEBUG_DISPLAY', true );
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
